# Generated by Django 5.1.3 on 2024-12-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blog_category_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
    ]
